server:
  port: 80080
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/forezp/SpringcloudConfig/   # 配置存放配置文件的git地址
          search-paths: respo      # 配置仓库路径
          username: 185601452@qq.com
          password: 111111
      label: master  # 配置仓库的分支
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://192.168.1.139:8761/eureka/


